### ISSUE TITLE
Random errors 'Worker 1 initial preflight failure. Aborting.' in Swarm log

### ISSUE THREAD

**Issue by vogoltsov** [hawkmoth-studio/perforce-docker#25]
```
Fail create ctx on the connecting client.
Failed to initialize SSL library.
NetSslTransport::SslClientInit SSL_load_error_strings: error:0909006C:PEM routines:get_name:no start line: Success
 in /opt/perforce/swarm/library/P4/Connection/Extension.php:477
Stack trace:
#0 /opt/perforce/swarm/library/P4/Connection/AbstractConnection.php(1010): P4\Connection\Extension->doConnect()
#1 /opt/perforce/swarm/library/P4/Connection/AbstractConnection.php(710): P4\Connection\AbstractConnection->connect()
#2 /opt/perforce/swarm/library/P4/Connection/AbstractConnection.php(403): P4\Connection\AbstractConnection->run('info')
#3 /opt/perforce/swarm/module/Queue/src/Controller/IndexController.php(343): P4\Connection\AbstractConnection->getInfo()
#4 /opt/perforce/swarm/module/Queue/src/Controller/IndexController.php(115): Queue\Controller\IndexController->preflight()
#5 /opt/perforce/swarm/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Queue\Controller\IndexController->workerAction()
#6 /opt/perforce/swarm/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#7 /opt/perforce/swarm/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#8 /opt/perforce/swarm/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(105): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#9 /opt/perforce/swarm/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#10 /opt/perforce/swarm/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#11 /opt/perforce/swarm/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#12 /opt/perforce/swarm/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#13 /opt/perforce/swarm/public/index.php(65): Laminas\Mvc\Application->run()
#14 {main}
```

**Comment by vogoltsov** [comment]
The problem arises only when running Swarm with HTTPS support enabled and P4D running with SSL turned on. This leads me to believe that there is some interference between Apache's HTTPS handling and P4's SSL support.

Can't tell if this was introduced with latest OpenSSL updated (unlikely, the issue is still present on Ubuntu 16.04 with OpenSSL 1.0.0) or if it was always there.
